name: uidev
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.0
  google_fonts:
  carousel_pro: ^1.0.0
  salomon_bottom_bar: ^2.0.0
  animated_drawer: ^0.0.4
  intl: ^0.16.1
  data_connection_checker: ^0.3.4
  http: ^0.12.0+4
  percent_indicator: ^2.1.3
  colorful_safe_area: ^0.2.1
  date_picker_timeline: ^1.2.1
  flutter_datetime_picker: ^1.4.0
  dropdown_formfield: ^0.1.3
  get: ^3.24.0
  flutter_icons: ^1.1.0
  charts_flutter: ^0.9.0
  settings_ui: ^0.5.0
  typicons_flutter: ^0.4.2
  url_launcher: ^5.7.10
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  google_sign_in: ^4.5.9
  firebase_auth: ^0.20.0+1
  liquid_swipe: ^1.5.0
  provider: ^4.3.3
  flex_color_picker: ^1.1.3
  shared_preferences: ^0.5.12+4
  after_layout: ^1.0.7+2
  syncfusion_flutter_datepicker: ^18.4.44-beta
  uuid: ^2.2.2
  animated_bottom_navigation_bar: ^0.2.1
  persistent_bottom_nav_bar: ^3.1.0
  circular_reveal_animation: ^1.1.5
  bubble_tab_indicator: ^0.1.4
  flutter_screenutil: ^1.0.2
  line_awesome_flutter: ^1.0.1
  flare_flutter: ^2.0.6
  audioplayers: ^0.17.4
  progress_state_button: ^1.0.2
  stop_watch_timer: ^0.4.0
  progress_indicators: ^0.1.5
  gradient_widgets: ^0.5.2
  loading_animations: ^2.1.0

#  firebase_auth: ^0.18.4+1
#  firebase_dynamic_links: ^0.5.1
#  cloud_firestore: ^0.14.4
#  firebase_core : ^0.5.0
#  flutter_facebook_login: ^3.0.0
#  google_sign_in: ^4.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  moor_generator: ^2.1.1
  flutter_launcher_icons: "^0.7.3"
  # test:
  #   sdk: flutter
#  integration_test:
#    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/facebook.png
    - assets/twitter.png
    - assets/google.png
    - assets/company.png
    - assets/
    - assets/3d/
    - assets/welcome_page.png
    - assets/workspace.png
    - assets/collections/
    - assets/product/
    - assets/images/
    - assets/mode/
    - assets/artwork/
    - assets/waiting.png
    - assets/sw.png
    - assets/WaterArtboards.flr
    - assets/beep-07.wav
    - assets/time/png/
    - assets/Prj/
    - assets/clock/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bebas
      fonts:
        - asset: fonts/bebas_neue/BebasNeue-Regular.otf
    - family: Coco
      fonts:
        - asset: fonts/coco/Cocogoose-Classic-Medium-trial.ttf
    - family: Sans
      fonts:
        - asset: fonts/sansation/Sansation_Bold.ttf
    - family: Var
      fonts:
        - asset: fonts/VarelaRound-Regular.ttf
    - family: icon
      fonts:
        - asset: fonts/icon.ttf
    - family: theme
      fonts:
        - asset: fonts/theme/TTHoves-Medium.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages